{% set version = "0.0.9" %}
{% set python_min = "3.10" %}

package:
  name: python-help2man
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/help2man/help2man-{{ version }}.tar.gz
  sha256: 57fa18ed59ee94952a2341153eae34fc90020cb4ebb26ce8a7324334119cf81a

build:
  entry_points:
    - help2man = help2man.__main__:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - jinja2
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - shtab
    - tomli
  run:
    - python >={{ python_min }}
    - jinja2

test:
  imports:
    - help2man
  commands:
    - pip check
    - help2man --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Freed-Wu/help2man
  summary: Convert --help and --version to man page.
  dev_url: https://github.com/Freed-Wu/help2man
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
